# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5dedd8d9ea5b34431b9994cb43a38024c8d2d87b2d582c87c74052491656b5300637dde3eaafa8551c0ba3081de20d799b704ab2ad0a4285aaeebfd784ccdfc2

test:
  secret_key_base: 682fe57738e6b4440d1d9e76d26f5926873360e540b0c0f4ad52ebb644b9fad5546e4ede8f3fc93414c6e451754112e4b9d3f95d5f80c491e82b07089b3cba43

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
